### ISSUE TITLE
gcop_comm/gcop_trajectory_visualizer.h

### ISSUE THREAD

**Issue by gouyiyong** [jhu-asco/aerial_autonomy#217]
hi,
i found there is no .h file and i also check the https://github.com/jhu-asco/gcop_ros_packages, but still no
![image](https://user-images.githubusercontent.com/26245593/61622428-0bc32400-ac75-11e9-8f04-d22ae95403f3.png)

**Comment by msheckells** [comment]
Thanks for reporting this issue.  I updated the public version of the gcop_ros_packages repo and added install instructions to the aerial_autonomy README.
